### Ctrl + Alt + R on the right line to run with VSCODE

@baseUrl = https://allestaco.niclas-sieveneck.de:5000/v1

### FILE: user.py

### Login
# @name login
POST {{baseUrl}}/user/login HTTP/1.1
content-type: application/json

{
    "benutzername": "ntr0py123", 
    "rolle": "käufer", 
    "password_encrypt": "1234"
}


### Login GET

GET {{baseUrl}}/user/login HTTP/1.1


### Logoff

GET {{baseUrl}}/user/logoff HTTP/1.1
#Cookie: session_id={{login.response.cookies.session_id}}


### User Info

GET {{baseUrl}}/user/info/1 HTTP/1.1


### Username check -> True

GET {{baseUrl}}/user/username/check/ntr0py HTTP/1.1


### Username check -> False

GET {{baseUrl}}/user/username/check/ntr0py1234234 HTTP/1.1


### Register

POST {{baseUrl}}/user/register HTTP/1.1
content-type: application/json

{
    "vorname": "Niclas", 
    "nachname": "Sieveneck", 
    "benutzername": "ntr0py1234", 
    "email": "info@niclas-sieveneck.de", 
    "rolle": "käufer", 
    "password_encrypt": "1234"
}


### FILE: article.py

### Article Add

POST {{baseUrl}}/article
Content-Type: application/json 

{
    "titel": "TacoTest2", 
    "verkaeufer_id": "1", 
    "beschreibung": "Ein Test Taco!", 
    "preis": "10.99", 
    "bild": "bild", 
    "status": "verfügbar", 
    "bestand": 5, 
    "kategorie": "Taco"
}

### Article Get

GET {{baseUrl}}/article/2


### Article by user
GET {{baseUrl}}/article/user/12


### Article Delete

DELETE {{baseUrl}}/article/10


### Article picutre get

GET {{baseUrl}}/article/picture/3


### Search for aticle
GET {{baseUrl}}/article/search/sauce


### Muliple aticles
GET {{baseUrl}}/article/multiple/2/4


#### FILE: user-cart.py

### Add to cart

POST {{baseUrl}}/user/cart
Content-Type: application/json 

{
  "anzahl": 3,
  "artikel_id": 3,
  "benutzer_id": 6,
  "verkaeufer_id": 5
}


### Get cart

GET {{baseUrl}}/user/cart


### Delete cart

DELETE  {{baseUrl}}/user/cart/3


### FILE: user_purchase.py

### Purchase get

GET {{baseUrl}}/user/purchase


### Purchase Cart

POST {{baseUrl}}/user/purchase

### Purchase delete

DELETE {{baseUrl}}/user/purchase


### FILE: article_views.py

### views add
POST {{baseUrl}}/article/views/3
Content-Type: application/json 

{
    "anzahl": 69
}


### views add via json
POST {{baseUrl}}/article/views
Content-Type: application/json 

{
    "artikel_id": 2,
    "anzahl": 69
}

### views get
GET {{baseUrl}}/article/views/2

### views delete
DELETE {{baseUrl}}/article/views/3


### FILE: user_reviews.py

### Reviews get

GET {{baseUrl}}/user/reviews/1


### Reviews add
POST {{baseUrl}}/user/reviews/6
Content-Type: application/json 

{
    "kommentar": "Das ist ein Kommentar",
    "rolle_des_bewerteten": "käufer",
    "sterne": 3
}


### Review delete
DELETE {{baseUrl}}/user/reviews/6


