version: '3'

services:
  # Pyhon container with flask
  api:
    build:
      context: ../backend
      dockerfile: ../docker/backend/Dockerfile
    image: hrw/api
    container_name: api
    restart: unless-stopped
    ### for testing:
    volumes:
      - ../backend:/usr/src/app
  
  # Best practise for flask
  api-proxy:
    image: nginx:stable-alpine
    container_name: api-proxy
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes: 
      - ./backend/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./cert/fullchain.pem:/etc/ssl/fullchain.pem
      - ./cert/privkey.pem:/etc/ssl/privkey.pem
    depends_on:
      - api

  # React+Vite frontend build by npm builder
  frontend:
    image: nginx:stable-alpine
    container_name: frontend
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./cert/fullchain.pem:/etc/ssl/fullchain.pem
      - ./cert/privkey.pem:/etc/ssl/privkey.pem
    depends_on:
      - api
      - api-proxy
