version: '3'

### Verion for use with nginx-pm in front!

services:
  # Pyhon container with flask
  api:
    build:
      context: ../backend
      dockerfile: ../docker/backend/Dockerfile
    image: hrw/api
    container_name: api
    restart: unless-stopped
    ### for testing:
    volumes:
      - ../backend:/usr/src/app
    depends_on:
      - tacodb
    networks:
      - network1
  
  # Best practise for flask
  api-proxy:
    image: docker.io/nginx:stable-alpine
    container_name: api-proxy
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes: 
      - ./backend/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./cert/fullchain.pem:/etc/ssl/fullchain.pem
      - ./cert/privkey.pem:/etc/ssl/privkey.pem
    depends_on:
      - api
    networks:
      - network1

  frontend:
    image: docker.io/nginx:stable-alpine
    container_name: frontend
    restart: unless-stopped
    # Port Mapping -> For testing
    ports:
      - "8081:80" # ngnix-pm
      - "9443:443" # nginx-pm
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./cert/fullchain.pem:/etc/ssl/fullchain.pem
      - ./cert/privkey.pem:/etc/ssl/privkey.pem
      - ../frontend/:/usr/share/nginx/html
    depends_on:
      - api
      - api-proxy
    networks:
      - network1

  tacodb:
    image: docker.io/mariadb:latest
    container_name: tacodb
    restart: unless-stopped
    #ports:
    #  - "3306:3306"
    environment:
      DB_MYSQL_HOST: "tacodb"
      MYSQL_ROOT_PASSWORD: "J8FIXMY6IROGCCA84DTuzs"
      MYSQL_DATABASE: "taco"
      MYSQL_USER: "taco"
      MYSQL_PASSWORD: "erb6dbfnsm47ptk90i9sw87"
    volumes:
      - ../database:/var/lib/mysql
    networks:
      - network1

  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - 8082:80
    environment:
      - MYSQL_ROOT_PASSWORD=J8FIXMY6IROGCCA84DTuzs
      - PMA_HOST=tacodb
      - PMA_USER=root
      - PMA_PASSWORD=J8FIXMY6IROGCCA84DTuzs
    networks:
      - network1

networks:
  network1:
    name: nginx-pm_default
    external: true


