# Rechte für `taco`@`%`

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, FILE, INDEX, ALTER, CREATE TEMPORARY TABLES, EXECUTE, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON *.* TO `taco`@`%` IDENTIFIED BY PASSWORD '*7CA0A190BED49E7D08519F51A8F873A9E2FDEB08';

GRANT ALL PRIVILEGES ON `taco`.* TO `taco`@`%`;