openapi: 3.0.3
info:
  title: Alles Taco - 1.0
  description: |-
    Alles Taco API 1.0
  version: 1.0.0

paths:
    ## article_views.py
    /v1/article/views/{article_id}:
      get:
        summary: Get views of an article
        description: Response the views of a given article by id.
        parameters:
          - name: article_id
            in: path
            description: ID of the article
            required: true
            schema:
              type: integer
        responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/article_views'
      delete:
        summary: Deletes all views of an article
        description: Deletes all views of an article by id.
        parameters:
          - name: article_id
            in: path
            description: ID of the article
            required: true
            schema:
              type: integer
        responses:
          '204':
            description: successful operation
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Status_ok'
          '405':
            description: Method Not Allowed
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Method_not_allowed'

    /v1/article/views:
      post:
        summary: Edit views of an article
        description: Edits the views of a given article by id.
        requestBody:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/article_views'
        responses:
          '201':
            description: successful operation
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Status_ok'
          '403':
            description: no login
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/No_login'
          '405':
            description: Method Not Allowed
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Method_not_allowed'

    ## article.py
    /v1/article/{article_id}:
      get:
        summary: Get an article
        description: Response a given article by id.
        parameters:
          - name: article_id
            in: path
            description: ID of the article
            required: true
            schema:
              type: integer
        responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/article'
      delete:
        summary: Deletes an article
        description: Deletes an article by id.
        parameters:
          - name: article_id
            in: path
            description: ID of the article
            required: true
            schema:
              type: integer
        responses:
          '204':
            description: successful operation
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Status_ok'
          '405':
            description: Method Not Allowed
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Method_not_allowed'

    /v1/article:
      post:
        summary: Adds a new article
        description: Adds a new article.
        requestBody:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/article'
        responses:
          '201':
            description: successful operation
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Status_ok'
          '403':
            description: no login
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/No_login'
          '405':
            description: Method Not Allowed
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Method_not_allowed'

      ## status.py
      /v1/status/api:
        get:
          summary: State of the API
          description: Shows the status of the API.
          responses:
            '200':
              description: successful operation
            
      /v1/status/db:
        get:
          summary: State of the Database
          description: Shows the status of the database.
          responses:
            '200':
              description: successful operation



### Componets:
components:
  schemas:
    # Default shit
    Status_ok:
      type: object
      properties:
        status:
          type: string
          example: ok
    
    Bad_request:
      type: object
      properties:
        code:
          type: integer
          example: 400
        status:
          type: string
          example: Bad Request
        description:
          type: string
          example: The browser (or proxy) sent a request that this server could not understand.
    
    Not_found:
      type: object
      properties:
        code:
          type: integer
          example: 404
        status:
          type: string
          example: Not found
        description:
          type: string
          example: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
    
    Method_not_allowed:
      type: object
      properties:
        code:
          type: integer
          example: 405
        status:
          type: string
          example: Method Not Allowed

    No_login:
      type: object
      properties:
        code:
          type: integer
          example: 403
        error:
          type: string
          example: No Login
    
    ## article_views.py
    article_views:
      type: object
      properties:
        artikel_id:
          type: integer
          example: 1
          required: false
        anzahl:
          type: integer
          example: 69
        aufrufer_id:
          type: integer
          example: 12

    ## article.py
    article:
      type: object
      properties:
        artikel_id:
          type: integer
          example: 1
          required: false
        beschreibung:
          type: string
          example: Ein Taco!
        bestand:
          type: integer
          example: 69   
        kategorie:
          type: string
          example: Taco
        preis:
          type: float
          example: 10.99
        status:
          type: string
          enum: [verfügbar, verkauft]
          example: verfügbar
        titel:
          type: string
          example: Taco mit Fleisch
        verkaeufer_id:
          type: integer
          example: 1