openapi: 3.0.3
info:
  title: Alles Taco - 1.0
  description: |-
    Alles Taco API 1.0
  version: 1.0.0

paths:
    ## article_views.py
    /v1/article/views/{article_id}:
      get:
        summary: Get views of an article
        tags:
          - article-views
        description: Response the views of a given article by id.
        parameters:
          - name: article_id
            in: path
            description: ID of the article
            required: true
            schema:
              type: integer
        responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/article_views'
      delete:
        summary: Deletes all views of an article
        tags:
          - article-views
        description: Deletes all views of an article by id.
        parameters:
          - name: article_id
            in: path
            description: ID of the article
            required: true
            schema:
              type: integer
        responses:
          '204':
            description: successful operation
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Status_ok'
          '405':
            description: Method Not Allowed
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Method_not_allowed'

    /v1/article/views:
      post:
        summary: Edit views of an article
        tags:
          - article-views
        description: Edits the views of a given article by id.
        requestBody:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/article_views'
        responses:
          '201':
            description: successful operation
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Status_ok'
          '403':
            description: no login
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/No_login'
          '405':
            description: Method Not Allowed
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Method_not_allowed'

    ## article.py
    /v1/article/{article_id}:
      get:
        summary: Get an article
        tags:
          - article
        description: Response a given article by id.
        parameters:
          - name: article_id
            in: path
            description: ID of the article
            required: true
            schema:
              type: integer
        responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/article'
      delete:
        summary: Deletes an article
        tags:
          - article
        description: Deletes an article by id.
        parameters:
          - name: article_id
            in: path
            description: ID of the article
            required: true
            schema:
              type: integer
        responses:
          '204':
            description: successful operation
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Status_ok'
          '405':
            description: Method Not Allowed
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Method_not_allowed'

    /v1/article:
      post:
        summary: Adds a new article
        tags:
          - article
        description: Adds a new article.
        requestBody:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/article'
        responses:
          '201':
            description: successful operation
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Status_ok'
          '403':
            description: no login
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/No_login'
          '405':
            description: Method Not Allowed
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Method_not_allowed'
    
    /v1/article/search/{search_str}:
      get:
        summary: Search for an article
        tags:
          - article-muliple
        description: Search for an article.
        parameters:
          - name: search_str
            in: path
            description: Search string
            required: true
            schema:
              type: integer
        responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/article'

    /v1/article/multiple/{first_article}/{last_aticle}:
      get:
        summary: Get multiple articles
        tags:
          - article-muliple
        description: Get multiple articles form a start number, to a end number.
        parameters:
          - name: first_aticle
            in: path
            description: First article to list
            required: true
            schema:
              type: integer
          - name: last_aticle
            in: path
            description: Last article to list, count from the first on onwards.
            required: true
            schema:
              type: integer
        responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/article'

    ## status.py
    /v1/system/status/api:
      get:
        summary: State of the API
        tags:
          - system
        description: Shows the status of the API.
        responses:
          '200':
            description: successful operation
          
    /v1/system/status/db:
      get:
        summary: State of the Database
        tags:
          - system
        description: Shows the status of the database.
        responses:
          '200':
            description: successful operation
    
    ## user_purchase.py
    /v1/user/purchase:
      post:
        summary: Add a purchase
        tags:
          - purchase
        description: Add a purchase to the Database.
        requestBody:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/purchase'
        responses:
          '201':
            description: successful operation
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Status_ok'
          '403':
            description: no login
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/No_login'
          '405':
            description: Method Not Allowed
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Method_not_allowed'    
      get:
        summary: Get all purchases for the current user
        tags:
          - purchase
        description: Get all purchases from the Database for the current user.
        responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/purchase'
          '403':
            description: no login
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/No_login'
          '405':
            description: Method Not Allowed
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Method_not_allowed'
      delete:
        summary: Delete all purchases for the current user
        tags:
          - purchase
        description: Delete all purchases from the Database for the current user.
        responses:
          '204':
            description: successful operation
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Status_ok'
          '403':
            description: no login
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/No_login'
          '405':
            description: Method Not Allowed
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Method_not_allowed'

    ## user_reviews.py
    /v1/user/reviews:
      post:
        summary: Add a review
        tags:
          - user-review
        description: Add a review
        requestBody:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/review'
        responses:
          '201':
            description: successful operation
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Status_ok'
          '403':
            description: no login
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/No_login'
          '405':
            description: Method Not Allowed
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Method_not_allowed'
      
    /v1/user/reviews/{user_id}:
      get:
        summary: Get all reviews for another user
        tags:
          - user-review
        description: Get all reviews for another user.
        parameters:
          - name: user_id
            in: path
            description: ID of the other user
            required: true
            schema:
              type: integer
        responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/review'
          '403':
            description: no login
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/No_login'

      delete:
        summary: Delete all reviews for another user
        tags:
          - user-review
        description: Delete all own reviews for another user.
        parameters:
          - name: user_id
            in: path
            description: ID of the other user
            required: true
            schema:
              type: integer
        responses:
          '204':
            description: successful operation
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Status_ok'
          '403':
            description: no login
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/No_login'
          '405':
            description: Method Not Allowed
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Method_not_allowed'

   ## user.py
    /v1/user/login:
      post:
        summary: Login for a user
        tags:
          - user-login
        description: Login for a user.
        requestBody:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user_login'
        responses:
          '201':
            description: successful operation
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/user'
          '405':
            description: Method Not Allowed
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Method_not_allowed'

    /v1/user/info/{user_id}:
      get:
        summary: Info for a user
        tags:
          - user
        description: Get info for a user.
        parameters:
          - name: user_id
            in: path
            description: ID of the other user
            required: true
            schema:
              type: integer
        responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/user'

    /v1/user/logoff:
      get:
        summary: Logoff the current user
        tags:
          - user-login
        description: Logoff the current user.
        responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Status_ok'

    /v1/user/username/check/{username}:
      get:
        summary: Check availabilty of a username
        tags:
          - user
        description: Check availabilty of a username.
        parameters:
          - name: username
            in: path
            description: Username to check.
            required: true
            schema:
              type: integer
        responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Status_ok'

    /v1/user/register:
      post:
        summary: Register a new user
        tags:
          - user-login
        description: Register a new user.
        requestBody:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user_register'
        responses:
          '201':
            description: successful operation
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Status_ok'
          '405':
            description: Method Not Allowed
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Method_not_allowed'

### Componets:
components:
  schemas:
    # Default shit
    Status_ok:
      type: object
      properties:
        status:
          type: string
          example: ok
    
    Bad_request:
      type: object
      properties:
        code:
          type: integer
          example: 400
        status:
          type: string
          example: Bad Request
        description:
          type: string
          example: The browser (or proxy) sent a request that this server could not understand.
    
    Not_found:
      type: object
      properties:
        code:
          type: integer
          example: 404
        status:
          type: string
          example: Not found
        description:
          type: string
          example: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
    
    Method_not_allowed:
      type: object
      properties:
        code:
          type: integer
          example: 405
        status:
          type: string
          example: Method Not Allowed

    No_login:
      type: object
      properties:
        code:
          type: integer
          example: 403
        error:
          type: string
          example: No Login
    
    ## article_views.py
    article_views:
      type: object
      properties:
        artikel_id:
          type: integer
          example: 1
          required: false
        anzahl:
          type: integer
          example: 69
        aufrufer_id:
          type: integer
          example: 12

    ## article.py
    article:
      type: object
      properties:
        artikel_id:
          type: integer
          example: 1
          required: false
        beschreibung:
          type: string
          example: Ein Taco!
        bestand:
          type: integer
          example: 69   
        kategorie:
          type: string
          example: Taco
        preis:
          type: float
          example: 10.99
        status:
          type: string
          enum: [verfügbar, verkauft]
          example: verfügbar
        titel:
          type: string
          example: Taco mit Fleisch
        verkaeufer_id:
          type: integer
          example: 1

    ## user_purchase.py
    purchase:
      type: object
      properties:
        artikel_id:
          type: integer
          example: 1
        kaeufer_id:
          type: integer
          example: 6
        kauf_id:
          type: integer
          example: 3
          required: false
        kaupreis:
          type: float
          example: 10.99
        versanddaten:
          type: string
          example: Lieferung am 01.01.2024
    
    ## user_reviews.py
    review:
      type: object
      properties:
        bewerter_id:
          type: integer
          example: 6
        bewerteter_id:
          type: integer
          example: 1
        bewertung_id:
          type: integer
          example: 1
          required: false
        kommentar:
          type: string
          example: Das ist ein Kommentar.
        rolle_des_bewerteten:
          type: string
          enum: [käufer, verkäufer]
          example: käufer
        sterne:
          type: integer
          example: 4

    ## user.py
    user:
      type: object
      properties:
        benutzer_id:
          type: integer
          example: 1
        benutzername:
          type: string
          example: ntr0py
        email:
          type: string
          example: info@niclas-sieveneck.de
        nachname:
          type: string
          example: Sieveneck
        rolle:
          type: string
          enum: [käufer, verkäufer]
          example: käufer
        vorname:
          type: string
          example: Niclas
      
    user_register:
      type: object
      properties:
        benutzername:
          type: string
          example: ntr0py
        email:
          type: string
          example: info@niclas-sieveneck.de
        nachname:
          type: string
          example: Sieveneck
        rolle:
          type: string
          enum: [käufer, verkäufer]
          example: käufer
        vorname:
          type: string
          example: Niclas
        password_encrypt:
          type: string
          example: 71d41999a926cf9983d9094b6237a62312ec2e33

    user_login:
      type: object
      properties:
        benutzername:
          type: string
          example: ntr0py
        password_encrypt:
          type: string
          example: 71d41999a926cf9983d9094b6237a62312ec2e33



### Tags:
tags:
  - name: article
    description: Add, Get or Delte atricles.
  - name: article-muliple
    description: Get muliple articles or search
  - name: article-views
    description: Views of articles
  - name: user-review
    description: Reviews of articles
  - name: system
    description: System status querys.
  - name: purchase
    description: Add, Get or Delte purchases.
  - name: user
    description: Everything user related
  - name: user-login
    description: Login, register, logoff